version: '3.9'


services:
 #Mongodb services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:  
     - 2717:27017
    volumes:
      - mongo_db:/data/db

  #Node js API services
  api:
    build: .
    ports:
      - 3000:8000
    volumes:
      - .:/usr/src/app
    environment:
       PORT: 8000
       MONGODB_URL:  mongodb://mongo_db:27017/newstudentdb
       MONGODB_NAME: newstudentdb
    depends_on:
      - mongo_db
    
volumes:
  mongo_db: {}